### ISSUE TITLE
Want to use latest version

### ISSUE THREAD

**Issue by otukutun** [sizuhiko/cakephp-fabricate-adaptor#17]
Hello, Thank you for creating great test tool! I'm excited to use it and I'm considering to introduce this on my CakePHP Project. 

But I got some errors on version 0.2.2. And I found that you updated some code but not published on packagest. So Would you publish latest version to packagest?

I'd like to use this patch. REF: https://github.com/sizuhiko/cakephp-fabricate-adaptor/commit/bbac3772704d5a1a202635811cf0e645f070792e

**Comment by sizuhiko** [comment]
I have pushed new version v0.3.0.
Please check it !

**Comment by otukutun** [comment]
Thank you for publishing it and your quick response!
